# Generated by Django 4.1.13 on 2024-06-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('rented', 'Rented'), ('returned', 'Returned')], default='requested', max_length=10),
        ),
    ]
